"""
create three green particles that all move to the right and have different velocities
Generated by Tölvera MoE system with code weaving.
"""

import taichi as ti
from tolvera import Tolvera, run

def main(**kwargs):
    tv = Tolvera(n=3, species=1, **kwargs)

    @ti.kernel
    def init_particles():
        # Deactivate all particles first
        for i in range(tv.pn):
            tv.p.field[i].active = 0.0

        # Particle creation
        for i in range(3):
         tv.p.field[i].pos = ti.Vector(ti.random() * 4096)
         tv.p.field[i].vel = ti.Vector([ti.random(), ti.random()])
         tv.p.field[i].active = 1.0
         tv.p.field[i].species = 0

    @ti.kernel
    def update_particles():
        for i in range(3):
            if tv.p.field[i].active > 0:
                tv.p.field[i].pos += tv.p.field[i].vel
                # Wrap around screen
                if tv.p.field[i].pos[0] > tv.x:
                    tv.p.field[i].pos[0] = 0.0
                if tv.p.field[i].pos[0] < 0:
                    tv.p.field[i].pos[0] = tv.x

    @ti.kernel
    def draw_particles():
        tv.px.background(0.0, 0.0, 0.0)

        for i in range(3):
            if tv.p.field[i].active > 0:
                pos = tv.p.field[i].pos
                x = ti.cast(pos[0], ti.i32)
                y = ti.cast(pos[1], ti.i32)
                size = ti.cast(tv.p.field[i].size, ti.i32)

                species_id = tv.p.field[i].species
                color = tv.s.species.field[species_id].rgba

                tv.px.circle(x, y, size, color, fill=1)

    # Default green color
    tv.s.species.field[0].rgba = ti.Vector([0.0, 1.0, 0.0, 1.0])

    initialized = ti.field(ti.i32, shape=())
    initialized[None] = 0

    @tv.render
    def _():
        if initialized[None] == 0:
            init_particles()
            initialized[None] = 1

        update_particles()
        draw_particles()

        return tv.px

if __name__ == '__main__':
    try:
        run(main)
    except KeyboardInterrupt:
        print("\nExiting.")
