"""
Products of Programmatic Experts (PoE) Core Implementation

This module implements the core PoE system for Tölvera particle behaviors using dynamically generated LLM code.
"""

import taichi as ti
import numpy as np
from typing import List, Dict, Any
import logging
import time
import linecache

from .poe_logger import get_logger

logger = logging.getLogger(__name__)
csv_logger = get_logger()


class SimpleProgrammaticExpert:

    def __init__(
            self,
            name: str,
            code: str,
            weight: float = 1.0,
            expert_type: str = "force"):
        self.name = name
        self.code = code
        self.weight = weight
        self.expert_type = expert_type  # "force" or "interaction"
        self.function = None
        self.metadata = {}


@ti.data_oriented
class PoEBehaviorSystem:

    def __init__(self, tolvera_instance):
        self.tv = tolvera_instance
        self.experts = []

        # Integration kernel (generated by LLM)
        self._integration_kernel = None

        # Track generated code
        self.generated_expert_code = {}  # Dict mapping expert name -> code
        self.generated_kernel_code = None
        self.state_definitions = {}  # Dict mapping state name -> state definition
        self.has_interactions = False  # Flag for kernel complexity

        logger.info(f"Initialized PoE system with {self.tv.pn} particles")

    def add_state_definition(self, state_result):
        """Store generated state definitions."""
        state_name = state_result.get("state_name", "unknown")
        self.state_definitions[state_name] = state_result
        logger.info(f"Added state definition: {state_name}")

    async def regenerate_integration_kernel(
            self, synthesizer, state_definitions):
        if not self.experts:
            logger.info("No experts available - clearing integration kernel")
            self._integration_kernel = None
            return True

        logger.info(
            f"Regenerating integration kernel for {len(self.experts)} experts")

        # Pass expert type information to kernel generation
        expert_info = [{
            'name': expert.name,
            'weight': expert.weight,
            'expert_type': getattr(expert, 'expert_type', 'force')
        } for expert in self.experts]

        # Update interaction flag
        self.has_interactions = any(
            e.get('expert_type') == 'interaction' for e in expert_info)

        # Collect natural language descriptions of experts for logging
        expert_descriptions = [
            expert.metadata.get(
                "description",
                expert.name) for expert in self.experts]
        user_description_for_kernel = f"Integration kernel for experts: {'; '.join(expert_descriptions)}"

        start_time = time.time()
        try:
            result = await synthesizer.synthesize_integration_kernel(
                expert_info, self.state_definitions)
            synthesis_time_ms = (time.time() - start_time) * 1000

            # None of this is necessary, but it's nice to have for the CSV
            # Log synthesis attempt
            csv_logger.log_synthesis_attempt(
                user_description=user_description_for_kernel,
                llm_prompt="",
                raw_response="",
                extracted_code=result.get(
                    "code",
                    ""),
                success=True,
                errors=[],
                model_name=synthesizer.client.model_name if hasattr(
                    synthesizer,
                    'client') else "unknown",
                expert_name=result.get(
                    "name",
                    None),
                synthesis_time_ms=synthesis_time_ms,
                synthesis_type="kernel",
                included_experts=[
                    expert.name for expert in self.experts],
                expert_codes=self.generated_expert_code.copy())

            self.generated_kernel_code = result['code']

            # Combine all expert and kernel code into a single string
            all_code = "\n\n".join(
                [expert.code for expert in self.experts] + [self.generated_kernel_code])

            # Use a unique name for the fake file to avoid cache collisions
            # (this took me longer to figure out than I care to admit)
            source_name = f"<poe_generated_kernel_{time.time_ns()}>"

            # Put the combined code into linecache
            linecache.cache[source_name] = (
                len(all_code), None, [
                    line + '\n' for line in all_code.splitlines()], source_name)

            logger.info("Compiling combined expert and kernel code")
            logger.debug(f"Combined Code:\n{all_code}")

            # Create a fresh namespace
            namespace = {'ti': ti, 'np': np, 'tv': self.tv}

            # Compile the combined code
            code_obj = compile(all_code, source_name, 'exec')
            exec(code_obj, namespace)

            # Assign functions to experts
            for expert in self.experts:
                if expert.name in namespace:
                    expert.function = namespace[expert.name]

            self._integration_kernel = namespace[result['name']]

            logger.info("Integration kernel successfully regenerated")
            return True

        except Exception as e:
            synthesis_time_ms = (time.time() - start_time) * 1000
            logger.error(f"Error regenerating kernel: {e}", exc_info=True)
            csv_logger.log_synthesis_attempt(
                user_description=f"Integration kernel for {len(expert_info)} experts",
                llm_prompt="",
                raw_response="",
                extracted_code="",
                success=False,
                errors=[
                    str(e)],
                model_name="unknown",
                expert_name=None,
                synthesis_time_ms=synthesis_time_ms,
                synthesis_type="kernel",
                included_experts=[
                    expert.name for expert in self.experts],
                expert_codes=self.generated_expert_code.copy())
            return False

    def add_expert(self, expert: SimpleProgrammaticExpert):
        self.experts.append(expert)
        self.generated_expert_code[expert.name] = expert.code
        logger.info(f"Added expert {expert.name} with weight {expert.weight}")
        self._integration_kernel = None
        logger.info(
            f"Expert {expert.name} added - integration kernel invalidated and needs regeneration")

    def set_expert_weight(self, expert_name: str, weight: float):
        for expert in self.experts:
            if expert.name == expert_name:
                expert.weight = weight
                logger.info(f"Updated weight for {expert_name} to {weight}")
                return
        logger.warning(f"Expert {expert_name} not found")

    def get_expert_info(self) -> List[Dict[str, Any]]:
        return [{
            "name": expert.name,
            "weight": expert.weight,
            "code_preview": expert.code[:200] + "..." if len(expert.code) > 200 else expert.code
        } for expert in self.experts]

    def clear_experts(self):
        self.experts.clear()
        self.generated_expert_code.clear()
        self._integration_kernel = None
        logger.info("Cleared all experts and integration kernel")
